In [2]:
scores = [78, 69, 65]
new_scores = [score + 3 for score in scores]
print(f"原始分數：{scores}")
print(f"加分後：{new_scores}")

原始分數：[78, 69, 65]
加分後：[81, 72, 68]


In [3]:
scores = [78, 69, 65]
new_scores = []
for score in scores:
    new_scores.append(score + 3)
print(f"原始分數：{scores}")
print(f"加分後：{new_scores}")

原始分數：[78, 69, 65]
加分後：[81, 72, 68]


In [1]:
scores = [78, 69, 65]
scores * 2


[78, 69, 65, 78, 69, 65]

In [2]:
scores = [78, 69, 65]
scores + [100, 90, 80]

[78, 69, 65, 100, 90, 80]

In [3]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores)) # 輸出：<class 'numpy.ndarray'>
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [4]:
students = np.array([
    [78, 69, 65],
    [100, 90, 80],
    [88, 77, 66]
    ]) 
students

array([[ 78,  69,  65],
       [100,  90,  80],
       [ 88,  77,  66]])

In [5]:
students.ndim, students.shape, students.size, students.dtype    

(2, (3, 3), 9, dtype('int32'))

In [6]:
students[0,0]

78

In [7]:
students[0, :]

array([78, 69, 65])

In [9]:
students[:,:2]

array([[ 78,  69],
       [100,  90],
       [ 88,  77]])