In [2]:
scores = [78, 69, 65]
new_scores = [score + 3 for score in scores]
print(f"原始分數：{scores}")
print(f"加分後：{new_scores}")

原始分數：[78, 69, 65]
加分後：[81, 72, 68]


In [3]:
scores = [78, 69, 65]
new_scores = []
for score in scores:
    new_scores.append(score + 3)
print(f"原始分數：{scores}")
print(f"加分後：{new_scores}")

原始分數：[78, 69, 65]
加分後：[81, 72, 68]


In [1]:
scores = [78, 69, 65]
scores * 2


[78, 69, 65, 78, 69, 65]

In [2]:
scores = [78, 69, 65]
scores + [100, 90, 80]

[78, 69, 65, 100, 90, 80]

In [11]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores)) # 輸出：<class 'numpy.ndarray'>
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [14]:
students = np.array([
    [78, 69, 65],
    [100, 90, 80],
    [88, 77, 66]
    ]) 
students

array([[ 78,  69,  65],
       [100,  90,  80],
       [ 88,  77,  66]])

In [5]:
students.ndim, students.shape, students.size, students.dtype    

(2, (3, 3), 9, dtype('int32'))

In [15]:
students[0,0]

78

In [17]:
students[0, :]

array([78, 69, 65])

In [18]:
students[:,:2]

array([[ 78,  69],
       [100,  90],
       [ 88,  77]])

In [23]:
students[0,0] = 100
students



array([[100,  69,  65],
       [100,  90,  80],
       [ 88,  77,  66]])

In [25]:
import pandas as pd 

pd.DataFrame(students, columns=['國文', '英文', '數學'])

pd.DataFrame(data=students, columns=['國文', '英文', '數學'], index=['小明', '小美', '小華'])

國文  英文  數學
小明  100  69  65
小美  100  90  80
小華   88  77  66

In [34]:
# 產生隨機分數資料
data = np.random.randint(60, high=101, size=(50,5))

# 建立 DataFrame，使用整個 data 矩陣而不是只取第一列
students = pd.DataFrame(data, columns=['國文', '英文', '數學', '自然', '社會'])
students

國文   英文   數學   自然  社會
0    77   83   73   93  81
1    67  100   67   81  86
2    67   79   76   94  80
3    90   75   70   98  95
4    67   91   60   97  69
5    64   79   89   75  93
6    83   65   60  100  85
7    69   94   70   78  89
8    97   83   62   63  64
9    78   82   60   64  61
10   98   84   82   84  74
11   78   88   91   73  63
12   88   83   80   81  98
13   89   70   82   84  93
14   64   89   73   74  72
15   93   96   82   91  89
16   83   97   60   68  99
17   72   90   88   78  79
18   65   66   87   82  60
19   61   94   82   72  92
20   70   72   73   89  87
21   78   75   90   89  88
22   65   73   73   93  77
23   75   61   87   94  90
24   70   63   83   99  75
25   63   71   64   60  88
26   84   93   60   64  80
27   80   76   79   84  88
28   66   84   90   80  74
29   85   66   76   69  96
30   83   61  100   60  60
31   76   62   98   94  87
32   90   94   72   79  67
33   61   70   61   87  74
34  100   88   64   69  84
35   75   98   86   80  84
36   99   81   91   77  71
37   71   80  100   60  77
38   95   78   74   69  90
39   61   66   90   76  81
40   84   87   86   60  84
41   77   78   84   62  92
42   84   98   76   68  77
43   78   67   92   79  61
44   88   97   97   90  78
45   88   70   70   90  90
46   84   73   72   84  99
47   60   95   97   73  89
48   75   63   73   99  88
49   92   75   82   76  60

In [35]:
# 產生隨機分數資料
data = np.random.randint(60, high=101, size=(50,5))

# 建立 DataFrame，使用整個 data 矩陣
students = pd.DataFrame(data, columns=['國文', '英文', '數學', '自然', '社會'])

# 計算各科目平均分數
subject_means = students.mean()

print("各科目平均分數：")
print("-" * 30)
for subject, mean in subject_means.items():
    print(f"{subject}: {mean:.2f} 分")

各科目平均分數：
------------------------------
國文: 76.90 分
英文: 80.68 分
數學: 78.76 分
自然: 82.28 分
社會: 81.26 分


In [36]:
import random

# 常見姓氏
last_names = ['陳', '林', '黃', '張', '李', '王', '吳', '劉', '蔡', '楊']

# 常見名字用字
first_names = '明華志豪文婷佳君偉婷怡雯宏軒冠宇佳怡志偉俊傑靜怡'

# 產生隨機姓名
def generate_name():
    last = random.choice(last_names)
    first = ''.join(random.sample(first_names, 2))
    return last + first

# 產生50個隨機姓名
names = [generate_name() for _ in range(50)]

# 建立 DataFrame
students = pd.DataFrame(
    data,
    columns=['國文', '英文', '數學', '自然', '社會'],
    index=names
)

# 顯示結果
print("學生成績表：")
print(students)

學生成績表：
      國文   英文  數學  自然   社會
黃文豪   75   61  70  68   93
吳志婷   99   89  89  82   95
李傑俊   62   63  70  81   94
蔡軒華   67   84  85  87   90
吳傑志   75   86  80  82   63
劉宇冠   87   81  75  94   81
吳軒宇   99   88  81  96   65
蔡冠婷   64   92  81  75   68
林宏華   68   75  83  83   66
王軒君   83   94  60  83   79
楊佳軒  100   66  67  92   97
劉婷靜   88   88  67  60   97
吳佳傑   89   73  68  93   95
王宇怡   85   78  74  73   70
楊志宇   85   61  73  97   93
陳明佳   62   99  81  80   70
楊傑婷   82   95  72  88  100
王文怡   68   89  71  67   72
劉婷豪   68   62  86  78   84
陳志宇   75   89  77  82   67
陳靜宏   64   84  80  90   70
蔡偉怡   65   70  78  85   97
王冠明   84   80  73  76   79
李君志   67   72  96  69   96
陳文靜   76   60  66  94   86
吳志偉   95   83  75  66   73
林華軒   71   93  87  92   91
楊宇婷  100  100  82  91   86
楊婷偉   61   80  92  65   86
李傑怡   81   87  71  75   70
楊宏怡   70   66  65  93   64
林怡佳   99   95  67  89   85
楊志君   65   94  76  69   96
劉佳俊   82   77  88  86   76
李怡佳   85   93  69  92   94
楊軒傑   61   72  89  90

In [38]:
names = [f"學生{i+1:02d}" for i in range(50)]  # 產生 學生01 到 學生50
names

['學生01',
 '學生02',
 '學生03',
 '學生04',
 '學生05',
 '學生06',
 '學生07',
 '學生08',
 '學生09',
 '學生10',
 '學生11',
 '學生12',
 '學生13',
 '學生14',
 '學生15',
 '學生16',
 '學生17',
 '學生18',
 '學生19',
 '學生20',
 '學生21',
 '學生22',
 '學生23',
 '學生24',
 '學生25',
 '學生26',
 '學生27',
 '學生28',
 '學生29',
 '學生30',
 '學生31',
 '學生32',
 '學生33',
 '學生34',
 '學生35',
 '學生36',
 '學生37',
 '學生38',
 '學生39',
 '學生40',
 '學生41',
 '學生42',
 '學生43',
 '學生44',
 '學生45',
 '學生46',
 '學生47',
 '學生48',
 '學生49',
 '學生50']

In [39]:
import random

# 常見姓氏
last_names = ['陳', '林', '黃', '張', '李', '王', '吳', '劉', '蔡', '楊']

# 常見名字用字
first_names = '明華志豪文婷佳君偉婷怡雯宏軒冠宇佳怡志偉俊傑靜怡'

# 產生隨機姓名
def generate_name():
    last = random.choice(last_names)
    first = ''.join(random.sample(first_names, 2))
    return last + first

# 產生50個隨機姓名
names = [generate_name() for _ in range(50)]

# 將名字寫入檔案
with open('names.txt', 'w', encoding='utf-8') as file:
    # 每個名字寫入一行
    for name in names:
        file.write(name + '\n')

print("名字已儲存到 names.txt 檔案中")

# 確認檔案內容
with open('names.txt', 'r', encoding='utf-8') as file:
    content = file.read()
print("\n檔案內容預覽：")
print(content[:100] + "...")  # 只顯示前面一部分

名字已儲存到 names.txt 檔案中

檔案內容預覽：
蔡志偉
黃怡明
吳華婷
陳俊婷
楊宏偉
陳豪偉
吳豪婷
張怡靜
王偉冠
林靜雯
陳明豪
陳雯宏
楊婷雯
張怡傑
楊華靜
黃華冠
林文婷
楊佳傑
劉雯怡
王文華
楊華冠
張明婷
黃怡文
楊軒雯
楊怡軒
...


In [40]:
# 讀取現有的名字
with open('names.txt', 'r', encoding='utf-8') as file:
    names = file.read().splitlines()

# 產生學號並與名字配對
student_data = []
for i, name in enumerate(names, 1):
    student_id = f'A1143033{i:03d}'  # 格式化學號 001~050
    student_data.append(f'{student_id} {name}')

# 寫入更新後的資料到檔案
with open('names.txt', 'w', encoding='utf-8') as file:
    for student in student_data:
        file.write(student + '\n')

print("已更新 names.txt 檔案，加入學號")

# 確認檔案內容
print("\n更新後的檔案內容預覽：")
with open('names.txt', 'r', encoding='utf-8') as file:
    print(file.read())

已更新 names.txt 檔案，加入學號

更新後的檔案內容預覽：
A1143033001 蔡志偉
A1143033002 黃怡明
A1143033003 吳華婷
A1143033004 陳俊婷
A1143033005 楊宏偉
A1143033006 陳豪偉
A1143033007 吳豪婷
A1143033008 張怡靜
A1143033009 王偉冠
A1143033010 林靜雯
A1143033011 陳明豪
A1143033012 陳雯宏
A1143033013 楊婷雯
A1143033014 張怡傑
A1143033015 楊華靜
A1143033016 黃華冠
A1143033017 林文婷
A1143033018 楊佳傑
A1143033019 劉雯怡
A1143033020 王文華
A1143033021 楊華冠
A1143033022 張明婷
A1143033023 黃怡文
A1143033024 楊軒雯
A1143033025 楊怡軒
A1143033026 劉怡佳
A1143033027 楊俊怡
A1143033028 楊君宇
A1143033029 吳偉靜
A1143033030 張婷君
A1143033031 黃宇冠
A1143033032 楊華婷
A1143033033 蔡偉佳
A1143033034 蔡志豪
A1143033035 劉怡靜
A1143033036 吳志怡
A1143033037 陳明傑
A1143033038 陳志軒
A1143033039 蔡華佳
A1143033040 張雯豪
A1143033041 王傑宇
A1143033042 蔡偉君
A1143033043 楊靜雯
A1143033044 張豪怡
A1143033045 林偉怡
A1143033046 劉婷偉
A1143033047 劉君宏
A1143033048 劉宇冠
A1143033049 林佳怡
A1143033050 陳偉婷



In [41]:
import numpy as np
import pandas as pd

# 讀取學生資料
with open('names.txt', 'r', encoding='utf-8') as file:
    students = file.read().splitlines()

# 將學號和姓名分開
student_ids = [s.split()[0] for s in students]
student_names = [s.split()[1] for s in students]

# 產生隨機成績 (50位學生 x 5個科目)
scores = np.random.randint(60, 101, size=(len(students), 5))

# 建立 DataFrame
df = pd.DataFrame(
    scores,
    columns=['國文', '英文', '數學', '理化', '公民'],
    index=student_ids
)

# 加入學生姓名欄位
df.insert(0, '姓名', student_names)

# 顯示結果
print("學生成績表：")
print("-" * 50)
print(df)

# 儲存成績表到 CSV 檔案
df.to_csv('student_scores.csv', encoding='utf-8-sig')
print("\n成績已儲存至 student_scores.csv")

# 顯示基本統計資料
print("\n各科統計資料：")
print("-" * 50)
print(df.describe().round(2))

學生成績表：
--------------------------------------------------
              姓名   國文   英文  數學   理化  公民
A1143033001  蔡志偉   80   61  85   70  79
A1143033002  黃怡明   71   68  61   81  63
A1143033003  吳華婷   69   67  93   96  90
A1143033004  陳俊婷   84   98  71   99  82
A1143033005  楊宏偉   98   82  92  100  60
A1143033006  陳豪偉   92   84  72   88  80
A1143033007  吳豪婷   87   79  97   61  86
A1143033008  張怡靜   79   98  89   80  85
A1143033009  王偉冠   99   94  70   86  65
A1143033010  林靜雯  100   89  80   84  69
A1143033011  陳明豪   89  100  60   62  87
A1143033012  陳雯宏   71   76  67   85  97
A1143033013  楊婷雯   80   99  63   66  69
A1143033014  張怡傑   68   73  65   74  85
A1143033015  楊華靜   61   69  75   74  90
A1143033016  黃華冠   72   76  60   67  66
A1143033017  林文婷   79   73  67   73  79
A1143033018  楊佳傑   93   72  68   82  60
A1143033019  劉雯怡   88   97  67   67  76
A1143033020  王文華   96   69  96   86  90
A1143033021  楊華冠   82   89  82   62  61
A1143033022  張明婷   90   96  91   81  94
A1143033023  黃怡文   93 